apiVersion: v1
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>To je test 123</title>
    </head>
    <body>

    <h1>123</h1>

    </body>
    </html>
kind: ConfigMap
metadata:
  name: kargo-demo-content
